version: '3.8'  

services:  
  json-server:  
    image: typicode/json-server  
    volumes:  
      - ./db.json:/data/db.json  
    ports:  
      - "3000:80"  

  app:  
    build:  
      context: .  
      dockerfile: Dockerfile # Tu Dockerfile para la aplicación  
    ports:  
      - "8080:8080" # Puerto de tu aplicación  
    depends_on:  
      - json-server